version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "8000:80"
    depends_on:
      - php
      - rails
  php:
    build: ./php
    volumes:
      - ./php/www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
  rails:
    build: ./rails
    volumes:
      - ./rails:/app:cached
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY_BASE=top-secret
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=pass
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/etc/mysql/conf.d:ro
      - mysql-webapp-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
volumes:
  mysql-webapp-data:
